// All page copy, English and Spanish. Spanish copy needs native speaker review before launch.
export type Lang = "en" | "es";
export type Variant = "a" | "b" | "c";

const en = {
  meta: {
    title: "Asmi for Pros: same hours, more paid jobs",
    desc: "Paid jobs with no lead fees, plus a crew that handles office work by text or voice in 30+ languages.",
  },
  top: { textUs: "Text us", langLabel: "Language" },
  hero: {
    eyebrow: "",
    h1: { a: "Paid jobs. No lead fees.", b: "Paid jobs. No lead fees.", c: "Paid jobs. No lead fees." },
    sub: "Customers pay first. Asmi handles the office work by text or voice, so you have more time for jobs.",
    modes: "",
    chipTitle: "New paid job: AC tune-up",
    chipSub: "Thu 10 AM. You take home $255.",
    artAlt: "Riso illustration of a home service pro at work",
  },
  cta: "Join the waitlist",
  checks: ["Customer paid first", "One pro per job"],
  example: "EXAMPLE",
  live: {
    pros: (n: number) => `${n.toLocaleString("en-US")} pros on the list.`,
    left: (n: number, c: string) => `${n} spots left in ${c}.`,
    stickyLeft: (n: number, c: string) => `${n} founding spots left in ${c}`,
  },
  trust: {
    team: ["Team from ", "Meta", " and ", "Google"],
    backed: ["Backed by leaders at ", "Snap, Meta, Google"],
    biz: "local businesses worked with",
    aria: "See who is behind Asmi",
  },
  pain: {
    h2: "Sound familiar?",
    items: ["Paying for leads that never call back.", "Quotes and invoices at 10 PM.", "Chasing customers to get paid."],
    fix: "Asmi fixes all three.",
  },
  two: {
    h2: "Asmi does two things for you.",
    paidLabel: "Paid jobs",
    paidH3: "Jobs that are already paid for.",
    paidList: ["The customer pays before you show up.", "One pro per job. You never pay for a lead.", "You see your take-home, then take it or pass."],
    admit: "ADMIT ONE PRO",
    crewLabel: "AI crew",
    crewH3: "Help with the office work, by text or voice.",
    crewList: ["Answers when you cannot and books the work.", "Prepares quotes from photos, moves your day and orders parts.", "Sends invoices and follows up on money owed—in 30+ languages."],
    note: "Works on the customers you already have.",
    noteFree: " No charge on your own jobs.",
  },
  day: {
    h2: "A day with Asmi",
    sub: "Text or talk to it like someone on your crew. It handles the rest.",
    biz: "AI crew for Ramos Heating and Air",
    you: "You",
    replay: "Replay",
    roles: ["Answers", "Quotes", "Gets parts", "Finds jobs", "Reschedules", "Follows up"],
    msgs: {
      m1: "Morning. 4 jobs today, fastest route is set. Load a capacitor for Alder St. The Johnsons still owe $180.",
      m2: "You were under a sink, so I picked up. Dana, 14 Alder St, AC not cooling. She can do 3 PM. Book it?",
      m3: "Book it",
      s3: "BOOKED 3 PM",
      m4: "What's next?",
      m5: "Maple St. Their photos point to a bad igniter. Want me to order one for pickup on your way?",
      m6: "Yes",
      s6: "PARTS READY",
      m7: "Free hour at 1 PM. Paid job 2 miles away: AC tune-up. Customer already paid $300. You take home $255. Take it?",
      m8: "Take it",
      s8: "PAID JOB BOOKED",
      m9: "Running long. Push everything an hour.",
      m10: "Done. Paid job now 2 PM, Alder St now 4 PM. Both customers got a text.",
      m11: "Day closed. Invoices sent. $610 earned, $180 still owed, reminder sent. First stop tomorrow 8 AM.",
      s11: "DAY CLOSED",
    },
    receipt: { head: "End of day", earned: "Earned today", owed: "Still owed, reminder sent", paper: "Paperwork tonight", none: "None" },
    fine: "You keep your number and approve every booking. Callers always hear that Asmi is an AI assistant for your business.",
  },
  paid: {
    h2: "Paid jobs, not paid leads.",
    rate: "Commission starts at 15%. You see the exact amount before you accept.",
    job: "AC tune-up",
    when: "Thu 10 AM, 2 miles away",
    r1: "Customer paid first",
    r2: "Asmi keeps (starts at 15%)",
    tot: "You take home",
    take: "TAKE IT",
    pass: "PASS, NO COST",
    cmpL: "Lead sites",
    cmpR: "Asmi",
    rows: [
      ["$35 to $200+ per lead", "$0 upfront"],
      ["Same lead sent to several pros", "One pro per job"],
      ["Most never reply", "Customer already paid"],
      ["You pay, win or lose", "From 15%, only on completed jobs"],
    ],
    whereQ: "Where do paid jobs come from?",
    whereA: "More people now ask AI assistants to get things fixed at home. When they do, Asmi books a nearby pro, takes the payment first and holds it until the job is done.",
  },
  how: {
    h2: "How it works",
    steps: [
      ["Join the waitlist", "Tell us where you work and what you do."],
      ["Set up by text", "About 15 minutes when your area opens."],
      ["The AI crew starts. Paid jobs follow.", "Founding pros get paid jobs first."],
    ],
  },
  team: {
    h2: "Who is behind Asmi",
    rishiRole: "Co-founder and CEO",
    rishi: "Built Asia's largest tech platform for small store owners: 100,000+ shops. Backed by top investors and founders of DoorDash and Zoom.",
    satwikRole: "Co-founder and CTO",
    satwik: "Built AI systems at Meta (Facebook). PhD from Carnegie Mellon. Previously worked at Google.",
    letter: "We completed 5,000 home service tasks for customers. We saw good pros lose work to missed calls and pay for leads that went nowhere. Asmi fixes both: paid jobs with no lead fees, plus help with the office work.",
    sig: "Rish, CEO",
    qText: (n: string) => `Questions? Text us at ${n}.`,
    qEmail: (e: string) => `Questions? Email ${e}.`,
    backedBy: "Backed by leaders at",
    backers: [["Snap", ""], ["Meta", ""], ["Google", ""]],
    company: "",
    quote: "From a pro",
  },
  spots: {
    h2: "Founding spots are limited.",
    sub: "Paid jobs open city by city. Founding pros get them first.",
    taken: (t: number, c: number) => `${t} of ${c} taken`,
    joined: (n: number) => `${n} pros joined`,
    full: "WAITLIST ONLY",
    next: "Join for the next group.",
    recent: "Recent joins",
    when: { today: "today", yesterday: "yesterday", "this week": "this week" },
    defaultTrade: "Home service pro",
  },
  cities: {
    bay_area: "Bay Area",
    los_angeles: "Los Angeles",
    new_york: "New York",
    other: "Somewhere else",
  },
  citiesShort: { bay_area: "the Bay Area", los_angeles: "LA", new_york: "New York", other: "your area" },
  faq: {
    h2: "Straight answers",
    items: {
      catch: ["What is the catch?", "Free to join. On paid jobs Asmi brings you, commission starts at 15%. You see the exact amount before accepting. Nothing on your own jobs."],
      card: ["Do I need a credit card?", "No. Joining is free. No card, no contract."],
      number: ["Do I keep my number?", "Yes. Asmi picks up only the calls you miss, or when you switch it on while you are busy."],
      approve: ["Do I approve what Asmi books?", "Yes. Asmi asks before it books anything. On paid jobs you see your take-home first, then take it or pass."],
      free: ["Is the AI crew free?", "Yes on your own jobs. We only earn a share on paid jobs Asmi brings you."],
      app: ["Do I have to learn new software?", "No. You run Asmi by text or voice, like texting someone in your office."],
      where: ["Where do paid jobs come from?", ""],
      paid: ["How do I get paid?", "The customer pays first. We hold it and release it when the job is done."],
      callers: ["What will callers hear?", "Hi, this is Asmi, the AI assistant for (your business). It says that first, every call."],
      mine: ["Are my customers still mine?", "Yes. Your customers and your info stay yours. We never sell your number."],
      real: ["How can I trust Asmi?", "Asmi is built by Humint Labs, Inc. in Sunnyvale. Our founders built products used by 100,000+ small shops and AI assistants at Meta. We are backed by leaders from Snap, Meta and Suno."],
      start: ["Where are you starting?", "The Bay Area, Los Angeles and New York."],
      spanish: ["Does Asmi speak Spanish?", "Yes. Asmi talks to your customers in Spanish and 30+ other languages."],
      payout: ["How fast do I get paid out?", ""],
    } satisfies Record<string, [string, string]>,
  },
  final: { h2: "Paid jobs and an AI crew. Free to join." },
  footer: { questions: "Questions?", text: "Text", privacy: "", terms: "" },
  sheet: {
    workOrder: "WORK ORDER",
    close: "Close",
    h: "Join the waitlist",
    hSub: "Paid jobs with no lead fees, starting in the Bay Area, Los Angeles and New York.",
    where: "Where do you work?",
    name: "Your name",
    namePh: "First and last name",
    phone: "Mobile number",
    otherCity: "Your city",
    otherCityPh: "City, state",
    consentBold: "I agree Asmi may text or call me about the waitlist.",
    consentPre: "",
    terms: "",
    and: "",
    privacy: "",
    saving: "Saving...",
    under: "",
    errCity: "Pick where you work.",
    errName: "Add your name.",
    errPhone: "That number does not look right.",
    errOtherCity: "Add the city where you work.",
    errConsent: "Check the box so we can text you.",
    errNet: "That did not go through. Check your signal and try again.",
    s2h: "One last step.",
    s2sub: "Tell us what kind of work you do, then join the list.",
    trades: "Your trades",
    tradeList: ["Plumbing", "Electrical", "HVAC", "Handyman", "Roofing", "General contractor", "Cleaning", "Other"],
    whichTrade: "Which trade?",
    crew: "Crew size",
    crewList: ["Just me", "2 to 5", "6 to 10", "More than 10"],
    zip: "Zip code",
    biz: "Business name (optional)",
    email: "Email (optional)",
    errZip: "Zip codes have 5 digits.",
    errEmail: "That email does not look right.",
    save: "Join the waitlist",
    skip: "",
    onList: "ON THE LIST",
    inCity: (c: string) => `in ${c}`,
    onTheList: "on the list",
    step1: "We text you to confirm.",
    step2: (c: string) => `When ${c} opens, we set you up by text. About 15 minutes.`,
    step3: "Founding pros get paid jobs first.",
    knowPro: "Know a pro tired of paying for leads?",
    share: "Share link",
    textIt: "",
    copy: "Copy link",
    copied: "Copied",
    shareText: "Asmi sends paid jobs to pros. No lead fees. Join the waitlist:",
    bump: (n: number) => `Each pro who joins with your link moves you up ${n} spots.`,
    call: "Want a quick call with our team?",
    callBtn: "Yes, call me",
    callDone: "Done. Someone from Asmi will call you.",
  },
  // Exact consent text stored with each signup, in the language shown.
  consentText:
    "Asmi can text or call me about the waitlist.",
};

export type Dict = typeof en;

const es: Dict = {
  meta: {
    title: "Asmi para Pros: mismas horas, más trabajos pagados",
    desc: "Trabajos pagados sin pagar por leads, más ayuda con la oficina por texto o voz en más de 30 idiomas.",
  },
  top: { textUs: "Escríbenos", langLabel: "Idioma" },
  hero: {
    eyebrow: "",
    h1: { a: "Trabajos pagados. Sin pagar por leads.", b: "Trabajos pagados. Sin pagar por leads.", c: "Trabajos pagados. Sin pagar por leads." },
    sub: "El cliente paga primero. Asmi se encarga de la oficina por texto o voz para que tengas más tiempo para trabajar.",
    modes: "",
    chipTitle: "Nuevo trabajo pagado: mantenimiento de AC",
    chipSub: "Jue 10 AM. Te llevas $255.",
    artAlt: "Ilustración de un pro de servicios del hogar trabajando",
  },
  cta: "Únete a la lista",
  checks: ["El cliente ya pagó", "Un pro por trabajo"],
  example: "EJEMPLO",
  live: {
    pros: (n: number) => `${n.toLocaleString("en-US")} pros en la lista.`,
    left: (n: number, c: string) => `Quedan ${n} lugares en ${c}.`,
    stickyLeft: (n: number, c: string) => `Quedan ${n} lugares fundadores en ${c}`,
  },
  trust: {
    team: ["Equipo de ", "Meta", " y ", "Google"],
    backed: ["Respaldado por líderes en ", "Snap, Meta y Google"],
    biz: "negocios locales con los que hemos trabajado",
    aria: "Mira quién está detrás de Asmi",
  },
  pain: {
    h2: "¿Te suena?",
    items: ["Pagar por leads que nunca te contestan.", "Cotizaciones y facturas a las 10 PM.", "Perseguir clientes para que te paguen."],
    fix: "Asmi arregla las tres.",
  },
  two: {
    h2: "Asmi hace dos cosas por ti.",
    paidLabel: "Trabajos pagados",
    paidH3: "Trabajos que ya están pagados.",
    paidList: ["El cliente paga antes de que llegues.", "Un pro por trabajo. Nunca pagas por un lead.", "Ves lo que te llevas y decides si lo tomas o lo pasas."],
    admit: "ADMITE UN PRO",
    crewLabel: "Equipo de IA",
    crewH3: "Ayuda con la oficina, por texto o voz.",
    crewList: ["Contesta cuando tú no puedes y agenda el trabajo.", "Prepara cotizaciones con fotos, mueve tu día y pide piezas.", "Manda facturas y cobra lo pendiente en más de 30 idiomas."],
    note: "Funciona con los clientes que ya tienes.",
    noteFree: " Sin costo en tus propios trabajos.",
  },
  day: {
    h2: "Un día con Asmi",
    sub: "Escríbele o háblale como a alguien de tu equipo. Se encarga del resto.",
    biz: "Equipo de IA de Ramos Heating and Air",
    you: "Tú",
    replay: "Ver otra vez",
    roles: ["Contesta", "Cotiza", "Pide piezas", "Busca trabajos", "Reagenda", "Cobra"],
    msgs: {
      m1: "Buenos días. 4 trabajos hoy, la ruta más rápida está lista. Lleva un capacitor para Alder St. Los Johnson todavía deben $180.",
      m2: "Estabas debajo de un fregadero, así que contesté yo. Dana, 14 Alder St, el AC no enfría. Puede a las 3 PM. ¿Lo agendo?",
      m3: "Agéndalo",
      s3: "AGENDADO 3 PM",
      m4: "¿Qué sigue?",
      m5: "Maple St. Sus fotos apuntan a un encendedor malo. ¿Pido uno para que lo recojas en el camino?",
      m6: "Sí",
      s6: "PIEZAS LISTAS",
      m7: "Hora libre a la 1 PM. Trabajo pagado a 2 millas: mantenimiento de AC. El cliente ya pagó $300. Te llevas $255. ¿Lo tomas?",
      m8: "Lo tomo",
      s8: "TRABAJO PAGADO AGENDADO",
      m9: "Voy atrasado. Mueve todo una hora.",
      m10: "Listo. Trabajo pagado ahora a las 2 PM, Alder St a las 4 PM. Los dos clientes recibieron un texto.",
      m11: "Día cerrado. Facturas enviadas. $610 ganados, $180 pendientes, recordatorio enviado. Primera parada mañana 8 AM.",
      s11: "DÍA CERRADO",
    },
    receipt: { head: "Fin del día", earned: "Ganado hoy", owed: "Pendiente, recordatorio enviado", paper: "Papeleo esta noche", none: "Nada" },
    fine: "Te quedas con tu número y apruebas cada cita. Quien llama siempre escucha que Asmi es un asistente de IA de tu negocio.",
  },
  paid: {
    h2: "Trabajos pagados, no leads pagados.",
    rate: "La comisión empieza en 15%. Ves la cantidad exacta antes de aceptar.",
    job: "Mantenimiento de AC",
    when: "Jue 10 AM, a 2 millas",
    r1: "El cliente pagó primero",
    r2: "Asmi se queda (empieza en 15%)",
    tot: "Te llevas",
    take: "LO TOMO",
    pass: "PASO, SIN COSTO",
    cmpL: "Sitios de leads",
    cmpR: "Asmi",
    rows: [
      ["$35 a $200+ por lead", "$0 por adelantado"],
      ["El mismo lead va a varios pros", "Un pro por trabajo"],
      ["La mayoría nunca contesta", "El cliente ya pagó"],
      ["Pagas, ganes o pierdas", "Desde 15%, solo en trabajos terminados"],
    ],
    whereQ: "¿De dónde salen los trabajos pagados?",
    whereA: "Cada vez más gente le pide a asistentes de IA que les arreglen cosas en casa. Cuando lo hacen, Asmi agenda a un pro cercano, cobra primero y guarda el pago hasta que se termina el trabajo.",
  },
  how: {
    h2: "Cómo funciona",
    steps: [
      ["Únete a la lista", "Dinos dónde trabajas y qué haces."],
      ["Te configuramos por texto", "Unos 15 minutos cuando abra tu zona."],
      ["Empieza el equipo de IA. Luego llegan los trabajos pagados.", "Los pros fundadores reciben trabajos pagados primero."],
    ],
  },
  team: {
    h2: "Quién está detrás de Asmi",
    rishiRole: "Cofundador y CEO",
    rishi: "Construyó la plataforma tecnológica más grande de Asia para pequeños comerciantes: más de 100,000 tiendas. Respaldado por grandes inversionistas y los fundadores de DoorDash y Zoom.",
    satwikRole: "Cofundador y CTO",
    satwik: "Construyó sistemas de IA en Meta (Facebook). Doctorado de Carnegie Mellon. Antes trabajó en Google.",
    letter: "Completamos 5,000 trabajos de servicio del hogar para clientes. Vimos a buenos pros perder trabajo por llamadas perdidas y pagar por leads que no llevaban a nada. Asmi arregla las dos cosas: trabajos pagados sin pagar por leads, más ayuda con la oficina.",
    sig: "Rish, CEO",
    qText: (n: string) => `¿Preguntas? Escríbenos al ${n}.`,
    qEmail: (e: string) => `¿Preguntas? Escribe a ${e}.`,
    backedBy: "Respaldado por líderes en",
    backers: [["Snap", ""], ["Meta", ""], ["Google", ""]],
    company: "",
    quote: "De un pro",
  },
  spots: {
    h2: "Los lugares fundadores son limitados.",
    sub: "Los trabajos pagados abren ciudad por ciudad. Los pros fundadores los reciben primero.",
    taken: (t: number, c: number) => `${t} de ${c} tomados`,
    joined: (n: number) => `${n} pros se unieron`,
    full: "SOLO LISTA DE ESPERA",
    next: "Únete para el próximo grupo.",
    recent: "Se unieron hace poco",
    when: { today: "hoy", yesterday: "ayer", "this week": "esta semana" },
    defaultTrade: "Pro de servicios del hogar",
  },
  cities: {
    bay_area: "Bay Area",
    los_angeles: "Los Ángeles",
    new_york: "Nueva York",
    other: "Otro lugar",
  },
  citiesShort: { bay_area: "el Bay Area", los_angeles: "LA", new_york: "Nueva York", other: "tu zona" },
  faq: {
    h2: "Respuestas claras",
    items: {
      catch: ["¿Cuál es el truco?", "Unirte es gratis. En trabajos que trae Asmi, la comisión empieza en 15%. Ves la cantidad exacta antes de aceptar. Nada en tus propios trabajos."],
      card: ["¿Necesito tarjeta de crédito?", "No. Unirte es gratis. Sin tarjeta, sin contrato."],
      number: ["¿Me quedo con mi número?", "Sí. Asmi contesta solo las llamadas que no alcanzas, o cuando lo prendes mientras estás ocupado."],
      approve: ["¿Yo apruebo lo que Asmi agenda?", "Sí. Asmi te pregunta antes de agendar cualquier cosa. En los trabajos pagados primero ves lo que te llevas y decides si lo tomas o lo pasas."],
      free: ["¿El equipo de IA es gratis?", "Sí en tus propios trabajos. Solo ganamos una parte en los trabajos pagados que te trae Asmi."],
      app: ["¿Tengo que aprender un programa nuevo?", "No. Usas Asmi por texto o voz, como escribirle a alguien de tu oficina."],
      where: ["¿De dónde salen los trabajos pagados?", ""],
      paid: ["¿Cómo me pagan?", "El cliente paga primero. Guardamos el pago y te lo liberamos cuando se termina el trabajo."],
      callers: ["¿Qué escucha quien llama?", "Hola, soy Asmi, el asistente de IA de (tu negocio). Lo dice primero, en cada llamada."],
      mine: ["¿Mis clientes siguen siendo míos?", "Sí. Tus clientes y tu información son tuyos. Nunca vendemos tu número."],
      real: ["¿Cómo puedo confiar en Asmi?", "Asmi lo hace Humint Labs, Inc. en Sunnyvale. Sus fundadores crearon productos usados por más de 100,000 tiendas y asistentes de IA en Meta. Nos respaldan líderes de Snap, Meta y Suno."],
      start: ["¿Dónde empiezan?", "En el Bay Area, Los Ángeles y Nueva York."],
      spanish: ["¿Asmi habla español?", "Sí. Asmi habla con tus clientes en español y más de 30 idiomas."],
      payout: ["¿Qué tan rápido me pagan?", ""],
    },
  },
  final: { h2: "Trabajos pagados y un equipo de IA. Gratis para unirte." },
  footer: { questions: "¿Preguntas?", text: "Texto", privacy: "", terms: "" },
  sheet: {
    workOrder: "ORDEN DE TRABAJO",
    close: "Cerrar",
    h: "Únete a la lista",
    hSub: "Trabajos pagados sin pagar por leads, empezando en el Bay Area, Los Ángeles y Nueva York.",
    where: "¿Dónde trabajas?",
    name: "Tu nombre",
    namePh: "Nombre y apellido",
    phone: "Número de celular",
    otherCity: "Tu ciudad",
    otherCityPh: "Ciudad, estado",
    consentBold: "Acepto que Asmi me mande textos o llame sobre la lista de espera.",
    consentPre: "",
    terms: "",
    and: "",
    privacy: "",
    saving: "Guardando...",
    under: "",
    errCity: "Escoge dónde trabajas.",
    errName: "Pon tu nombre.",
    errPhone: "Ese número no se ve bien.",
    errOtherCity: "Añade la ciudad donde trabajas.",
    errConsent: "Marca la casilla para poder mandarte textos.",
    errNet: "No se pudo enviar. Revisa tu señal y vuelve a intentar.",
    s2h: "Un último paso.",
    s2sub: "Dinos qué tipo de trabajo haces y luego únete a la lista.",
    trades: "Tus oficios",
    tradeList: ["Plomería", "Electricidad", "HVAC", "Handyman", "Techos", "Contratista general", "Limpieza", "Otro"],
    whichTrade: "¿Cuál oficio?",
    crew: "Tamaño del equipo",
    crewList: ["Solo yo", "2 a 5", "6 a 10", "Más de 10"],
    zip: "Código postal",
    biz: "Nombre del negocio (opcional)",
    email: "Email (opcional)",
    errZip: "El código postal tiene 5 dígitos.",
    errEmail: "Ese email no se ve bien.",
    save: "Únete a la lista",
    skip: "",
    onList: "EN LA LISTA",
    inCity: (c: string) => `en ${c}`,
    onTheList: "en la lista",
    step1: "Te mandamos un texto para confirmar.",
    step2: (c: string) => `Cuando abra ${c}, te configuramos por texto. Unos 15 minutos.`,
    step3: "Los pros fundadores reciben trabajos pagados primero.",
    knowPro: "¿Conoces a un pro cansado de pagar por leads?",
    share: "Compartir link",
    textIt: "",
    copy: "Copiar link",
    copied: "Copiado",
    shareText: "Asmi manda trabajos pagados a pros. Sin pagar por leads. Únete a la lista:",
    bump: (n: number) => `Cada pro que se une con tu link te sube ${n} lugares.`,
    call: "¿Quieres una llamada rápida con nuestro equipo?",
    callBtn: "Sí, llámenme",
    callDone: "Listo. Alguien de Asmi te va a llamar.",
  },
  consentText:
    "Asmi me puede mandar textos o llamar sobre la lista de espera.",
};

// Trade keys stored in the database (language independent).
export const TRADE_KEYS = ["plumbing", "electrical", "hvac", "handyman", "roofing", "general_contractor", "cleaning", "other"] as const;
export const CREW_KEYS = ["just_me", "2_5", "6_10", "10_plus"] as const;

export const dicts: Record<Lang, Dict> = { en, es };
